# Generated by Django 5.0.6 on 2024-11-14 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='applied',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='img',
        ),
    ]
