# Generated by Django 5.0.6 on 2024-11-14 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0002_remove_jobs_applied_remove_jobs_img'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='jobs',
            new_name='Sem_1',
        ),
    ]
