# Generated by Django 5.0.6 on 2024-11-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0004_sem_2_delete_internships'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sem_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('link', models.TextField()),
            ],
        ),
    ]
