# Generated by Django 5.0.6 on 2024-11-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0005_sem_3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('link', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Sem_1',
            new_name='Year_1',
        ),
        migrations.RenameModel(
            old_name='Sem_3',
            new_name='Year_2',
        ),
        migrations.DeleteModel(
            name='Sem_2',
        ),
    ]
