# Generated by Django 5.0.6 on 2024-11-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0006_year_3_rename_sem_1_year_1_rename_sem_3_year_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='year_1',
            name='link',
        ),
        migrations.RemoveField(
            model_name='year_2',
            name='link',
        ),
        migrations.RemoveField(
            model_name='year_3',
            name='link',
        ),
        migrations.AlterField(
            model_name='year_1',
            name='name',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='year_2',
            name='name',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='year_3',
            name='name',
            field=models.CharField(max_length=400),
        ),
    ]
