# Generated by Django 5.0.6 on 2024-11-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0007_remove_year_1_link_remove_year_2_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='year_1',
            name='link',
            field=models.TextField(default='https://classickcode-4zfw.onrender.com'),
        ),
        migrations.AddField(
            model_name='year_2',
            name='link',
            field=models.TextField(default='https://classickcode-4zfw.onrender.com'),
        ),
        migrations.AddField(
            model_name='year_3',
            name='link',
            field=models.TextField(default='https://classickcode-4zfw.onrender.com'),
        ),
    ]
